### ISSUE TITLE
How to add album list and switch albums

### ISSUE THREAD

**Issue by liseipi** [suragch/flutter_audio_service_demo#17]
How to add album list and switch albums ?
```
final _playlist = ConcatenatingAudioSource(children: []);
```
I want to achieve album list playback like this
[https://demo.koel.dev/#!/albums](https://demo.koel.dev/#!/albums)

**Comment by suragch** [comment]
Sorry, I haven't been working on this repo for over a year. You've probably already either solved your problem or abandoned it. Since this question is beyond the scope of the tutorial, I'm going to close it. But if you ask on Stack Overflow, I'll be glad to add a bounty to your question. Just ping me.
